title: Simran # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer @ <a href="https://www.optum.com/">Optum(UnitedHealth Group)</a>
  <br><br>
  <a href="mailto:simranpwc@gmail.com">Send an email</a>
  <br>
  <a href="https://www.linkedin.com/in/the-simran/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
